# Site settings
title: My Jekyll Site
description: A description of my site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
theme: my-jekyll-theme
# Other theme-specific settings go here

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-paginate
  - jekyll-sitemap
